[pytest]
# Thư mục tìm test
testpaths = app/test

# Hiện output chi tiết
addopts =
    -v
    --tb=short
    --no-header

# Tắt warning asyncio_mode
asyncio_mode = auto

# Bỏ qua warning của passlib, APScheduler, pytest-asyncio
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::pytest.PytestUnraisableExceptionWarning
